# coding: utf-8

"""
    Fincura Integration API

    This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****  # noqa: E501

    The version of the OpenAPI document: 1.2.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fincura.configuration import Configuration


class ApiKey(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'refresh_token': 'str',
        'tenant_id': 'str',
        'access_token': 'str',
        'expiration_date': 'datetime'
    }

    attribute_map = {
        'refresh_token': 'refresh_token',
        'tenant_id': 'tenant_id',
        'access_token': 'access_token',
        'expiration_date': 'expiration_date'
    }

    def __init__(self, refresh_token=None, tenant_id=None, access_token=None, expiration_date=None, local_vars_configuration=None):  # noqa: E501
        """ApiKey - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._refresh_token = None
        self._tenant_id = None
        self._access_token = None
        self._expiration_date = None
        self.discriminator = None

        self.refresh_token = refresh_token
        self.tenant_id = tenant_id
        if access_token is not None:
            self.access_token = access_token
        if expiration_date is not None:
            self.expiration_date = expiration_date

    @property
    def refresh_token(self):
        """Gets the refresh_token of this ApiKey.  # noqa: E501


        :return: The refresh_token of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this ApiKey.


        :param refresh_token: The refresh_token of this ApiKey.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and refresh_token is None:  # noqa: E501
            raise ValueError("Invalid value for `refresh_token`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                refresh_token is not None and len(refresh_token) > 2500):
            raise ValueError("Invalid value for `refresh_token`, length must be less than or equal to `2500`")  # noqa: E501

        self._refresh_token = refresh_token

    @property
    def tenant_id(self):
        """Gets the tenant_id of this ApiKey.  # noqa: E501


        :return: The tenant_id of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this ApiKey.


        :param tenant_id: The tenant_id of this ApiKey.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and tenant_id is None:  # noqa: E501
            raise ValueError("Invalid value for `tenant_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                tenant_id is not None and len(tenant_id) > 50):
            raise ValueError("Invalid value for `tenant_id`, length must be less than or equal to `50`")  # noqa: E501

        self._tenant_id = tenant_id

    @property
    def access_token(self):
        """Gets the access_token of this ApiKey.  # noqa: E501


        :return: The access_token of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this ApiKey.


        :param access_token: The access_token of this ApiKey.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def expiration_date(self):
        """Gets the expiration_date of this ApiKey.  # noqa: E501


        :return: The expiration_date of this ApiKey.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this ApiKey.


        :param expiration_date: The expiration_date of this ApiKey.  # noqa: E501
        :type: datetime
        """

        self._expiration_date = expiration_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiKey):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiKey):
            return True

        return self.to_dict() != other.to_dict()
