# coding: utf-8

"""
    Fincura Integration API

    This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****  # noqa: E501

    The version of the OpenAPI document: 1.2.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fincura.configuration import Configuration


class DataViewCalculatedValue(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'value': 'float',
        'error': 'str',
        'error_message': 'str',
        'footnotes': 'str',
        'line_item': 'DataViewCalculatedValueLineItem'
    }

    attribute_map = {
        'value': 'value',
        'error': 'error',
        'error_message': 'error_message',
        'footnotes': 'footnotes',
        'line_item': 'line_item'
    }

    def __init__(self, value=None, error=None, error_message=None, footnotes=None, line_item=None, local_vars_configuration=None):  # noqa: E501
        """DataViewCalculatedValue - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._value = None
        self._error = None
        self._error_message = None
        self._footnotes = None
        self._line_item = None
        self.discriminator = None

        self.value = value
        self.error = error
        self.error_message = error_message
        self.footnotes = footnotes
        self.line_item = line_item

    @property
    def value(self):
        """Gets the value of this DataViewCalculatedValue.  # noqa: E501


        :return: The value of this DataViewCalculatedValue.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DataViewCalculatedValue.


        :param value: The value of this DataViewCalculatedValue.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and value is None:  # noqa: E501
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def error(self):
        """Gets the error of this DataViewCalculatedValue.  # noqa: E501


        :return: The error of this DataViewCalculatedValue.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this DataViewCalculatedValue.


        :param error: The error of this DataViewCalculatedValue.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and error is None:  # noqa: E501
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def error_message(self):
        """Gets the error_message of this DataViewCalculatedValue.  # noqa: E501


        :return: The error_message of this DataViewCalculatedValue.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this DataViewCalculatedValue.


        :param error_message: The error_message of this DataViewCalculatedValue.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and error_message is None:  # noqa: E501
            raise ValueError("Invalid value for `error_message`, must not be `None`")  # noqa: E501

        self._error_message = error_message

    @property
    def footnotes(self):
        """Gets the footnotes of this DataViewCalculatedValue.  # noqa: E501


        :return: The footnotes of this DataViewCalculatedValue.  # noqa: E501
        :rtype: str
        """
        return self._footnotes

    @footnotes.setter
    def footnotes(self, footnotes):
        """Sets the footnotes of this DataViewCalculatedValue.


        :param footnotes: The footnotes of this DataViewCalculatedValue.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and footnotes is None:  # noqa: E501
            raise ValueError("Invalid value for `footnotes`, must not be `None`")  # noqa: E501

        self._footnotes = footnotes

    @property
    def line_item(self):
        """Gets the line_item of this DataViewCalculatedValue.  # noqa: E501


        :return: The line_item of this DataViewCalculatedValue.  # noqa: E501
        :rtype: DataViewCalculatedValueLineItem
        """
        return self._line_item

    @line_item.setter
    def line_item(self, line_item):
        """Sets the line_item of this DataViewCalculatedValue.


        :param line_item: The line_item of this DataViewCalculatedValue.  # noqa: E501
        :type: DataViewCalculatedValueLineItem
        """
        if self.local_vars_configuration.client_side_validation and line_item is None:  # noqa: E501
            raise ValueError("Invalid value for `line_item`, must not be `None`")  # noqa: E501

        self._line_item = line_item

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataViewCalculatedValue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataViewCalculatedValue):
            return True

        return self.to_dict() != other.to_dict()
