# coding: utf-8

"""
    Fincura Integration API

    This [REST API](https://en.wikipedia.org/wiki/Representational_state_transfer) allows you to interact with the Fincura processing and insights engine.   # Authentication  This API uses API keys generated from a Fincura User account. To get access to your User account, speak with you Fincura account manager.  # Accepted Media Types  | File&nbsp;Type&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | Extension(s)     | Content-Type(s) | | -------------------------------- |-------------- | ------------ | | PDF File | .pdf | `application/pdf` , `application/x-pdf` | | Excel File | .xls | `application/vnd.ms-excel`  | | Excel File | .xlsx | `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`  | | PNG Image | .png | `image/png`  | | GIF Image | .gif | `image/gif`  | | JPG Image | .jpg, .jpeg | `image/jpeg`  | | GIF Image | .gif | `image/gif`  |   # Getting Started  1. [Create a Borrower](#operation/createBorrower)  2. [Add a file](#operation/createDocumentFile) for that Borrower. 3. Analyze in the Fincura App  ****  # noqa: E501

    The version of the OpenAPI document: 1.2.3
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fincura.configuration import Configuration


class LoanPeriods(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'reporting_period': 'str',
        'preparation_type': 'str'
    }

    attribute_map = {
        'reporting_period': 'reporting_period',
        'preparation_type': 'preparation_type'
    }

    def __init__(self, reporting_period=None, preparation_type=None, local_vars_configuration=None):  # noqa: E501
        """LoanPeriods - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._reporting_period = None
        self._preparation_type = None
        self.discriminator = None

        self.reporting_period = reporting_period
        self.preparation_type = preparation_type

    @property
    def reporting_period(self):
        """Gets the reporting_period of this LoanPeriods.  # noqa: E501


        :return: The reporting_period of this LoanPeriods.  # noqa: E501
        :rtype: str
        """
        return self._reporting_period

    @reporting_period.setter
    def reporting_period(self, reporting_period):
        """Sets the reporting_period of this LoanPeriods.


        :param reporting_period: The reporting_period of this LoanPeriods.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and reporting_period is None:  # noqa: E501
            raise ValueError("Invalid value for `reporting_period`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                reporting_period is not None and len(reporting_period) > 200):
            raise ValueError("Invalid value for `reporting_period`, length must be less than or equal to `200`")  # noqa: E501

        self._reporting_period = reporting_period

    @property
    def preparation_type(self):
        """Gets the preparation_type of this LoanPeriods.  # noqa: E501


        :return: The preparation_type of this LoanPeriods.  # noqa: E501
        :rtype: str
        """
        return self._preparation_type

    @preparation_type.setter
    def preparation_type(self, preparation_type):
        """Sets the preparation_type of this LoanPeriods.


        :param preparation_type: The preparation_type of this LoanPeriods.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and preparation_type is None:  # noqa: E501
            raise ValueError("Invalid value for `preparation_type`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                preparation_type is not None and len(preparation_type) > 200):
            raise ValueError("Invalid value for `preparation_type`, length must be less than or equal to `200`")  # noqa: E501

        self._preparation_type = preparation_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoanPeriods):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LoanPeriods):
            return True

        return self.to_dict() != other.to_dict()
